---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

    volumes:
      - ${PWD}/data/service-volumes/.zookeeper-data:/var/lib/zookeeper/data
      - ${PWD}/data/service-volumes/.zookeeper-tx-logs:/var/lib/zookeeper/log